{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate","preciseIdentifier":"c:@M@Bricks@objc(pl)OTPFieldViewDelegate","text":"OTPFieldViewDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldview\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OTPFieldViewDelegate","preciseIdentifier":"c:@M@Bricks@objc(pl)OTPFieldViewDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Bricks12OTPFieldViewC8delegateAA0bC8Delegate_pSgvp","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView":{"role":"symbol","title":"OTPFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldView"}],"url":"\/documentation\/bricks\/otpfieldview"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate":{"role":"symbol","title":"OTPFieldViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldViewDelegate"}],"url":"\/documentation\/bricks\/otpfieldviewdelegate"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OTPFieldViewDelegate","preciseIdentifier":"c:@M@Bricks@objc(pl)OTPFieldViewDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/otpfieldview\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/title","value":"OTPFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/fragments","value":[{"kind":"identifier","text":"OTPFieldView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/title","value":"OTPFieldViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/fragments","value":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}