{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enteredOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldviewdelegate\/enteredotp(otp:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/otpfieldviewdelegate\/enteredotp(otp:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/enteredOTP(otp:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"enteredOTPWithOtp:"}],"role":"symbol","title":"enteredOTP(otp:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enteredOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@Bricks@objc(pl)OTPFieldViewDelegate(im)enteredOTPWithOtp:","required":true,"modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate":{"role":"symbol","title":"OTPFieldViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldViewDelegate"}],"url":"\/documentation\/bricks\/otpfieldviewdelegate"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate/enteredOTP(otp:)":{"navigatorTitle":[{"kind":"identifier","text":"enteredOTPWithOtp:"}],"role":"symbol","title":"enteredOTP(otp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enteredOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/enteredOTP(otp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bricks\/otpfieldviewdelegate\/enteredotp(otp:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enteredOTPWithOtp:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enteredOTPWithOtp:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"enteredOTPWithOtp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"otp"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/title","value":"OTPFieldViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/fragments","value":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1enteredOTP(otp:)\/title","value":"enteredOTPWithOtp:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1enteredOTP(otp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enteredOTPWithOtp:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}