{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otpTextFieldIndex"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldviewdelegate\/shouldbecomefirstresponderforotp(otptextfieldindex:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/otpfieldviewdelegate\/shouldbecomefirstresponderforotp(otptextfieldindex:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"}],"role":"symbol","title":"shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otpTextFieldIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@M@Bricks@objc(pl)OTPFieldViewDelegate(im)shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:","required":true,"modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate":{"role":"symbol","title":"OTPFieldViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldViewDelegate"}],"url":"\/documentation\/bricks\/otpfieldviewdelegate"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)":{"navigatorTitle":[{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"}],"role":"symbol","title":"shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otpTextFieldIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bricks\/otpfieldviewdelegate\/shouldbecomefirstresponderforotp(otptextfieldindex:)"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/title","value":"OTPFieldViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/fragments","value":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)\/title","value":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}