{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvloaderview\/didmovetosuperview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvloaderview\/didmovetosuperview()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLoaderView\/didMoveToSuperview()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"title":"didMoveToSuperview()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Bricks@objc(cs)GVLoaderView(im)didMoveToSuperview","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLoaderView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVLoaderView/didMoveToSuperview()":{"role":"symbol","title":"didMoveToSuperview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLoaderView\/didMoveToSuperview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"url":"\/documentation\/bricks\/gvloaderview\/didmovetosuperview()"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVLoaderView":{"role":"symbol","title":"GVLoaderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVLoaderView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLoaderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVLoaderView"}],"url":"\/documentation\/bricks\/gvloaderview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didMoveToSuperview"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToSuperview"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLoaderView~1didMoveToSuperview()\/title","value":"didMoveToSuperview"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLoaderView~1didMoveToSuperview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToSuperview"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLoaderView\/title","value":"GVLoaderView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLoaderView\/fragments","value":[{"kind":"identifier","text":"GVLoaderView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}