{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedCorner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/displaytype\/roundedcorner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/displaytype\/roundedcorner"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/roundedCorner","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedCorner"}],"title":"DisplayType.roundedCorner","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Bricks@E@DisplayType@DisplayTypeRoundedCorner","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType":{"role":"symbol","title":"DisplayType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayType"}],"url":"\/documentation\/bricks\/displaytype"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/roundedCorner":{"role":"symbol","title":"DisplayType.roundedCorner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedCorner"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/roundedCorner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}],"url":"\/documentation\/bricks\/displaytype\/roundedcorner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DisplayTypeRoundedCorner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/title","value":"DisplayType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/fragments","value":[{"kind":"identifier","text":"DisplayType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1roundedCorner\/title","value":"DisplayTypeRoundedCorner"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1roundedCorner\/fragments","value":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}