{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"square"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/displaytype\/square"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/displaytype\/square"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/square","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"square"}],"title":"DisplayType.square","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Bricks@E@DisplayType@DisplayTypeSquare","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayTypeSquare"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/square":{"role":"symbol","title":"DisplayType.square","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"square"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/square","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeSquare"}],"url":"\/documentation\/bricks\/displaytype\/square"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType":{"role":"symbol","title":"DisplayType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayType"}],"url":"\/documentation\/bricks\/displaytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DisplayTypeSquare"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DisplayTypeSquare"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DisplayTypeSquare"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1square\/title","value":"DisplayTypeSquare"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1square\/fragments","value":[{"kind":"identifier","text":"DisplayTypeSquare"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/title","value":"DisplayType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/fragments","value":[{"kind":"identifier","text":"DisplayType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}