{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvmultilinetextfield\/leftimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvmultilinetextfield\/leftimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftImage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convenience property to set an image directly instead of a left view"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"leftImage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Bricks@objc(cs)GVMultilineTextField(py)leftImage","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"leftImage"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/leftImage":{"role":"symbol","title":"leftImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Convenience property to set an image directly instead of a left view"}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftImage"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/leftimage"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField":{"role":"symbol","title":"GVMultilineTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"}],"abstract":[{"type":"text","text":"Text field with support for multiple lines."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMultilineTextField"}],"url":"\/documentation\/bricks\/gvmultilinetextfield"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"leftImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leftImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"leftImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1leftImage\/title","value":"leftImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1leftImage\/fragments","value":[{"kind":"identifier","text":"leftImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/title","value":"GVMultilineTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/fragments","value":[{"kind":"identifier","text":"GVMultilineTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}