{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphabet"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/keyboardtype\/alphabet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/keyboardtype\/alphabet"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphabet","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphabet"}],"title":"KeyboardType.alphabet","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Bricks@E@KeyboardType@KeyboardTypeAlphabet","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType":{"role":"symbol","title":"KeyboardType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"abstract":[{"type":"text","text":"Different input type for OTP fields."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardType"}],"url":"\/documentation\/bricks\/keyboardtype"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/alphabet":{"role":"symbol","title":"KeyboardType.alphabet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphabet"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphabet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}],"url":"\/documentation\/bricks\/keyboardtype\/alphabet"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"KeyboardTypeAlphabet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/title","value":"KeyboardType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/fragments","value":[{"kind":"identifier","text":"KeyboardType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1alphabet\/title","value":"KeyboardTypeAlphabet"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1alphabet\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}