{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextFieldBase","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextFieldBase","text":"GVTextFieldBase"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvinputfield\/textfield"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVInputField\/textField","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVTextFieldBase","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextFieldBase"}],"title":"textField","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Bricks12GVInputFieldC04textC0AA06GVTextC4BaseCvp","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVInputField"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextFieldBase":{"role":"symbol","title":"GVTextFieldBase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextFieldBase"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextFieldBase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVTextFieldBase"}],"url":"\/documentation\/bricks\/gvtextfieldbase"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVInputField/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVTextFieldBase","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextFieldBase"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVInputField\/textField","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvinputfield\/textfield"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVInputField":{"role":"symbol","title":"GVInputField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVInputField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVInputField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVInputField"}],"url":"\/documentation\/bricks\/gvinputfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextFieldBase\/title","value":"GVTextFieldBase"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextFieldBase\/fragments","value":[{"kind":"identifier","text":"GVTextFieldBase"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVInputField\/title","value":"GVInputField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVInputField\/fragments","value":[{"kind":"identifier","text":"GVInputField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}