{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"closure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField","text":"GVTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvfieldview\/ontextchanged(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onTextChanged(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"onTextChanged(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6Bricks11GVFieldViewC13onTextChangedyyyAA11GVTextFieldCcF","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView":{"role":"symbol","title":"GVFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVFieldView"}],"url":"\/documentation\/bricks\/gvfieldview"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField":{"role":"symbol","title":"GVTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVTextField"}],"url":"\/documentation\/bricks\/gvtextfield"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/onTextChanged(_:)":{"role":"symbol","title":"onTextChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onTextChanged(_:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/ontextchanged(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView\/title","value":"GVFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView\/fragments","value":[{"kind":"identifier","text":"GVFieldView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField\/title","value":"GVTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField\/fragments","value":[{"kind":"identifier","text":"GVTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}