{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField","text":"GVTextField"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvfieldview\/textfield"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textField","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField"}],"title":"textField","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Bricks11GVFieldViewC9textFieldAA06GVTextE0Cvp","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField":{"role":"symbol","title":"GVTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVTextField"}],"url":"\/documentation\/bricks\/gvtextfield"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textField","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/textfield"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView":{"role":"symbol","title":"GVFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVFieldView"}],"url":"\/documentation\/bricks\/gvfieldview"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField\/title","value":"GVTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField\/fragments","value":[{"kind":"identifier","text":"GVTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView\/title","value":"GVFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView\/fragments","value":[{"kind":"identifier","text":"GVFieldView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}