{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onFileSelected"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document","preciseIdentifier":"c:@M@Bricks@objc(cs)Document","text":"Document"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/filepicker\/present(from:onfileselected:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/FilePicker\/present(from:onFileSelected:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onFileSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"c:@M@Bricks@objc(cs)Document"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"present(from:onFileSelected:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6Bricks10FilePickerC7present4from02onB8SelectedySo16UIViewControllerC_yAA8DocumentCSgctF","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/FilePicker"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/Document":{"role":"symbol","title":"Document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Document"}],"url":"\/documentation\/bricks\/document"},"doc://org.cocoapods.Bricks/documentation/Bricks/FilePicker/present(from:onFileSelected:)":{"role":"symbol","title":"present(from:onFileSelected:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onFileSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"c:@M@Bricks@objc(cs)Document"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/FilePicker\/present(from:onFileSelected:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/filepicker\/present(from:onfileselected:)"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/FilePicker":{"role":"symbol","title":"FilePicker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilePicker"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/FilePicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FilePicker"}],"url":"\/documentation\/bricks\/filepicker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document\/title","value":"Document"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document\/fragments","value":[{"kind":"identifier","text":"Document"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1FilePicker\/title","value":"FilePicker"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1FilePicker\/fragments","value":[{"kind":"identifier","text":"FilePicker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}