{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userContentController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvwebviewcontroller\/usercontentcontroller(_:didreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvwebviewcontroller\/usercontentcontroller(_:didreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/userContentController(_:didReceive:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKScriptMessageHandler.userContentController(_:didReceive:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"title":"userContentController(_:didReceive:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Bricks@objc(cs)GVWebViewController(im)userContentController:didReceiveScriptMessage:","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVWebViewController":{"role":"symbol","title":"GVWebViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVWebViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVWebViewController"}],"url":"\/documentation\/bricks\/gvwebviewcontroller"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVWebViewController/userContentController(_:didReceive:)":{"role":"symbol","title":"userContentController(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/userContentController(_:didReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"url":"\/documentation\/bricks\/gvwebviewcontroller\/usercontentcontroller(_:didreceive:)"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userContentController:didReceiveScriptMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userContentController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userContentController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveScriptMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController\/title","value":"GVWebViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController\/fragments","value":[{"kind":"identifier","text":"GVWebViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController~1userContentController(_:didReceive:)\/title","value":"userContentController:didReceiveScriptMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController~1userContentController(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}