{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvcheckboxv2\/isselected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvcheckboxv2\/isselected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVCheckboxV2\/isSelected","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isSelected","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Bricks@objc(cs)GVCheckboxV2(py)selected","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"selected"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVCheckboxV2"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVCheckboxV2/isSelected":{"role":"symbol","title":"isSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVCheckboxV2\/isSelected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selected"}],"url":"\/documentation\/bricks\/gvcheckboxv2\/isselected"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVCheckboxV2":{"role":"symbol","title":"GVCheckboxV2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVCheckboxV2"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVCheckboxV2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVCheckboxV2"}],"url":"\/documentation\/bricks\/gvcheckboxv2"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"selected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"selected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVCheckboxV2~1isSelected\/title","value":"selected"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVCheckboxV2~1isSelected\/fragments","value":[{"kind":"identifier","text":"selected"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVCheckboxV2\/title","value":"GVCheckboxV2"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVCheckboxV2\/fragments","value":[{"kind":"identifier","text":"GVCheckboxV2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}