{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBottomSheetViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvbottomsheetviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvbottomsheetviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheet","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/buttonAction"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/basicInfo(title:titleAlignment:contentView:primaryButtonTitle:primaryButtonIcon:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/contentInfoIcon(icon:title:desc:type:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/contentInfoThumbnail(thumbnail:contentMode:title:desc:type:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBottomSheetViewController"}],"title":"GVBottomSheetViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVBottomSheetViewController","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVBottomSheetViewController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/contentInfoThumbnail(thumbnail:contentMode:title:desc:type:)":{"role":"symbol","title":"contentInfoThumbnail(thumbnail:contentMode:title:desc:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInfoThumbnail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"thumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVBottomSheetType","preciseIdentifier":"s:6Bricks17GVBottomSheetTypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/contentInfoThumbnail(thumbnail:contentMode:title:desc:type:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/contentinfothumbnail(thumbnail:contentmode:title:desc:type:)"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/basicInfo(title:titleAlignment:contentView:primaryButtonTitle:primaryButtonIcon:)":{"role":"symbol","title":"basicInfo(title:titleAlignment:contentView:primaryButtonTitle:primaryButtonIcon:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"basicInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"primaryButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"primaryButtonIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/basicInfo(title:titleAlignment:contentView:primaryButtonTitle:primaryButtonIcon:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/basicinfo(title:titlealignment:contentview:primarybuttontitle:primarybuttonicon:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/viewdidappear(_:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/contentInfoIcon(icon:title:desc:type:)":{"role":"symbol","title":"contentInfoIcon(icon:title:desc:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInfoIcon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"desc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVBottomSheetType","preciseIdentifier":"s:6Bricks17GVBottomSheetTypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/contentInfoIcon(icon:title:desc:type:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/contentinfoicon(icon:title:desc:type:)"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController":{"role":"symbol","title":"GVBottomSheetViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBottomSheetViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBottomSheetViewController"}],"url":"\/documentation\/bricks\/gvbottomsheetviewcontroller"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetView":{"role":"symbol","title":"GVBottomSheetView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBottomSheetView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBottomSheetView"}],"url":"\/documentation\/bricks\/gvbottomsheetview"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/buttonAction":{"role":"symbol","title":"buttonAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonAction"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"GVBottomSheetAction","preciseIdentifier":"s:6Bricks19GVBottomSheetActionO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/buttonAction","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/buttonaction"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/viewdidload()"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/initwithnibname:bundle:"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheet":{"role":"symbol","title":"GVBottomSheet","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBottomSheet"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBottomSheet"}],"url":"\/documentation\/bricks\/gvbottomsheet"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBottomSheetViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/bricks\/gvbottomsheetviewcontroller\/initwithcoder:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVBottomSheetViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVBottomSheetViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVBottomSheetViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/initWithCoder:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/initWithNibName:bundle:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBottomSheetViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBottomSheetView","preciseIdentifier":"c:@M@Bricks@objc(cs)GVBottomSheetView","text":"GVBottomSheetView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetViewController\/title","value":"GVBottomSheetViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetViewController\/fragments","value":[{"kind":"identifier","text":"GVBottomSheetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetView\/title","value":"GVBottomSheetView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetView\/fragments","value":[{"kind":"identifier","text":"GVBottomSheetView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBottomSheetViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}