{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Under the hood this is just a "},{"type":"codeVoice","code":"UITextView"},{"type":"text","text":" which aims to provide"},{"type":"text","text":" "},{"type":"text","text":"many of the functionalities currently available in the "},{"type":"codeVoice","code":"UITextField"},{"type":"text","text":" class."},{"type":"text","text":" "},{"type":"text","text":"Currently the following functionalities are supported:"}]}],"type":"aside","name":"NOTE"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Multiple lines"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customizable left view"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customizable placeholder"}]}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The following features are still missing:"}]}],"type":"aside","name":"To Do"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add support for displaying a right view"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"counter and input limit"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure when left\/right views will be shown using "},{"type":"codeVoice","code":"UITextField.leftViewMode"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvmultilinetextfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvmultilinetextfield"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UITextView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFindInteractionDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIKeyInput","doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDraggable","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDroppable","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInput","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInputTraits","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Text field with support for multiple lines."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"}],"title":"GVMultilineTextField","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVMultilineTextField","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVMultilineTextField"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/init(coder:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/init(frame:textContainer:maxCharacter:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/attributedText","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/isEnabled","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/isError","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/isPlaceholderScrollEnabled","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftImage","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftView","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftViewOrigin","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholder","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholderAlignment","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholderColor","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/text"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/didMoveToSuperview()","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/willMove(toSuperview:)"]}],"references":{"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/objc(pl)UIKeyInput":{"type":"unresolvable","title":"UIKit.UIKeyInput","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIKeyInput"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Bricks/objc(pl)UITextDroppable":{"type":"unresolvable","title":"UIKit.UITextDroppable","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDroppable"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/willMove(toSuperview:)":{"role":"symbol","title":"willMove(toSuperview:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toSuperview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/willMove(toSuperview:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willMoveToSuperview:"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/willmove(tosuperview:)"},"doc://org.cocoapods.Bricks/objc(cs)UITextView":{"type":"unresolvable","title":"UITextView","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UITextView"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemScrollableContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemScrollableContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemScrollableContainer"},"doc://org.cocoapods.Bricks/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.Bricks/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/text","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/text"},"doc://org.cocoapods.Bricks/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Bricks/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/init(frame:textContainer:maxCharacter:)":{"role":"symbol","title":"init(frame:textContainer:maxCharacter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextContainer","preciseIdentifier":"c:objc(cs)NSTextContainer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"maxCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/init(frame:textContainer:maxCharacter:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/init(frame:textcontainer:maxcharacter:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/isError":{"role":"symbol","title":"isError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/isError","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/iserror"},"doc://org.cocoapods.Bricks/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/placeholderColor":{"role":"symbol","title":"placeholderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Color to use to draw the placeholder string."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholderColor","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/placeholdercolor"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIFindInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIFindInteractionDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFindInteractionDelegate"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/didMoveToSuperview()":{"role":"symbol","title":"didMoveToSuperview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/didMoveToSuperview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/didmovetosuperview()"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/placeholder":{"role":"symbol","title":"placeholder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The string that is displayed when there is no other text in the text field."},{"type":"text","text":" "},{"type":"text","text":"This value is nil by default. The placeholder string is drawn using the color"},{"type":"text","text":" "},{"type":"text","text":"stored in "},{"type":"codeVoice","code":"self.placeholderColor"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/placeholder"},"doc://org.cocoapods.Bricks/objc(pl)UITextPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UITextPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/objc(pl)UITextInput":{"type":"unresolvable","title":"UIKit.UITextInput","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInput"},"doc://org.cocoapods.Bricks/objc(pl)UITextInputTraits":{"type":"unresolvable","title":"UIKit.UITextInputTraits","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInputTraits"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/objc(pl)UITextDraggable":{"type":"unresolvable","title":"UIKit.UITextDraggable","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDraggable"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/attributedText":{"role":"symbol","title":"attributedText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributedText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/attributedText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"attributedText"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/attributedtext"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/isPlaceholderScrollEnabled":{"role":"symbol","title":"isPlaceholderScrollEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaceholderScrollEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value that determines whether scrolling is enabled"},{"type":"text","text":" "},{"type":"text","text":"for the placeholder content."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/isPlaceholderScrollEnabled","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/isplaceholderscrollenabled"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/placeholderAlignment":{"role":"symbol","title":"placeholderAlignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderAlignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAlignment","preciseIdentifier":"c:@E@NSTextAlignment"}],"abstract":[{"type":"text","text":"Alignment for placeholder"}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholderAlignment","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/placeholderalignment"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/leftView":{"role":"symbol","title":"leftView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The overlay view displayed in the left side of the text field."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftView","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/leftview"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/leftViewOrigin":{"role":"symbol","title":"leftViewOrigin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"Point used as the origin for displaying the left view."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftViewOrigin","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/leftvieworigin"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/isEnabled","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilinetextfield\/isenabled"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/leftImage":{"role":"symbol","title":"leftImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Convenience property to set an image directly instead of a left view"}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftImage"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/leftimage"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/init(coder:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField":{"role":"symbol","title":"GVMultilineTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"}],"abstract":[{"type":"text","text":"Text field with support for multiple lines."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMultilineTextField"}],"url":"\/documentation\/bricks\/gvmultilinetextfield"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","title":"UIKit.UIContentSizeCategoryAdjusting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentSizeCategoryAdjusting"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVMultilineTextField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVMultilineTextField"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVMultilineTextField"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/attributedText","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/leftImage","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholder","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/text"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/didMoveToSuperview()","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/init(coder:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/willMove(toSuperview:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UITextView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1willMove(toSuperview:)\/title","value":"willMoveToSuperview:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1willMove(toSuperview:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToSuperview:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1text\/title","value":"text"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1didMoveToSuperview()\/title","value":"didMoveToSuperview"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1didMoveToSuperview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToSuperview"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1placeholder\/title","value":"placeholder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1placeholder\/fragments","value":[{"kind":"identifier","text":"placeholder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1attributedText\/title","value":"attributedText"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1attributedText\/fragments","value":[{"kind":"identifier","text":"attributedText"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1leftImage\/title","value":"leftImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1leftImage\/fragments","value":[{"kind":"identifier","text":"leftImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/title","value":"GVMultilineTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/fragments","value":[{"kind":"identifier","text":"GVMultilineTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}