{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVNudeButtonAbstract"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvnudebuttonabstract"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvnudebuttonabstract"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigNudeButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigNudeIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumNudeButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumNudeIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallNudeButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallNudeIconButton"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/10Kingfisher0A10CompatibleP","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract\/isEnabled"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract\/responseHandling()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVNudeButtonAbstract"}],"title":"GVNudeButtonAbstract","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVNudeButtonAbstract","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVNudeButtonAbstract"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVSmallNudeIconButton":{"role":"symbol","title":"GVSmallNudeIconButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVSmallNudeIconButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallNudeIconButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVSmallNudeIconButton"}],"url":"\/documentation\/bricks\/gvsmallnudeiconbutton"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVSmallNudeButton":{"role":"symbol","title":"GVSmallNudeButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVSmallNudeButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallNudeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVSmallNudeButton"}],"url":"\/documentation\/bricks\/gvsmallnudebutton"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBigNudeIconButton":{"role":"symbol","title":"GVBigNudeIconButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBigNudeIconButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigNudeIconButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBigNudeIconButton"}],"url":"\/documentation\/bricks\/gvbignudeiconbutton"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBigNudeButton":{"role":"symbol","title":"GVBigNudeButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBigNudeButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigNudeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBigNudeButton"}],"url":"\/documentation\/bricks\/gvbignudebutton"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMediumNudeIconButton":{"role":"symbol","title":"GVMediumNudeIconButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMediumNudeIconButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumNudeIconButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMediumNudeIconButton"}],"url":"\/documentation\/bricks\/gvmediumnudeiconbutton"},"doc://org.cocoapods.Bricks/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVNudeButtonAbstract":{"role":"symbol","title":"GVNudeButtonAbstract","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVNudeButtonAbstract"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVNudeButtonAbstract"}],"url":"\/documentation\/bricks\/gvnudebuttonabstract"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVNudeButtonAbstract/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract\/isEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/bricks\/gvnudebuttonabstract\/isenabled"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVNudeButtonAbstract/responseHandling()":{"role":"symbol","title":"responseHandling()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseHandling"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract\/responseHandling()","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvnudebuttonabstract\/responsehandling()"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMediumNudeButton":{"role":"symbol","title":"GVMediumNudeButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMediumNudeButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumNudeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMediumNudeButton"}],"url":"\/documentation\/bricks\/gvmediumnudebutton"},"doc://org.cocoapods.Bricks/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVRoundedButtonAbstract":{"role":"symbol","title":"GVRoundedButtonAbstract","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVRoundedButtonAbstract"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVRoundedButtonAbstract"}],"url":"\/documentation\/bricks\/gvroundedbuttonabstract"},"doc://org.cocoapods.Bricks/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/10Kingfisher0A10CompatibleP":{"type":"unresolvable","title":"Kingfisher.KingfisherCompatible","identifier":"doc:\/\/org.cocoapods.Bricks\/10Kingfisher0A10CompatibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContextMenuInteractionDelegate"},"doc://org.cocoapods.Bricks/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVNudeButtonAbstract"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVNudeButtonAbstract"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVNudeButtonAbstract"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVNudeButtonAbstract\/isEnabled"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigNudeButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigNudeIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumNudeButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumNudeIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallNudeButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallNudeIconButton"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVNudeButtonAbstract"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract","preciseIdentifier":"c:@M@Bricks@objc(cs)GVRoundedButtonAbstract","text":"GVRoundedButtonAbstract"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallNudeIconButton\/title","value":"GVSmallNudeIconButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallNudeIconButton\/fragments","value":[{"kind":"identifier","text":"GVSmallNudeIconButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallNudeButton\/title","value":"GVSmallNudeButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallNudeButton\/fragments","value":[{"kind":"identifier","text":"GVSmallNudeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigNudeIconButton\/title","value":"GVBigNudeIconButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigNudeIconButton\/fragments","value":[{"kind":"identifier","text":"GVBigNudeIconButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigNudeButton\/title","value":"GVBigNudeButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigNudeButton\/fragments","value":[{"kind":"identifier","text":"GVBigNudeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumNudeIconButton\/title","value":"GVMediumNudeIconButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumNudeIconButton\/fragments","value":[{"kind":"identifier","text":"GVMediumNudeIconButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVNudeButtonAbstract\/title","value":"GVNudeButtonAbstract"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVNudeButtonAbstract\/fragments","value":[{"kind":"identifier","text":"GVNudeButtonAbstract"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVNudeButtonAbstract~1isEnabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVNudeButtonAbstract~1isEnabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumNudeButton\/title","value":"GVMediumNudeButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumNudeButton\/fragments","value":[{"kind":"identifier","text":"GVMediumNudeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVRoundedButtonAbstract\/title","value":"GVRoundedButtonAbstract"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVRoundedButtonAbstract\/fragments","value":[{"kind":"identifier","text":"GVRoundedButtonAbstract"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}