{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVToastView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvtoastview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvtoastview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVToastView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVToastView\/init(child:minHeight:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVToastView\/createView()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVToastView"}],"title":"GVToastView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVToastView","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVToastView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVToastView/createView()":{"role":"symbol","title":"createView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVToastView\/createView()","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvtoastview\/createview()"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.Bricks/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVToastView":{"role":"symbol","title":"GVToastView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVToastView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVToastView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVToastView"}],"url":"\/documentation\/bricks\/gvtoastview"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UIView"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVToastView/init(child:minHeight:)":{"role":"symbol","title":"init(child:minHeight:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"child"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVToastView\/init(child:minHeight:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvtoastview\/init(child:minheight:)"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance"},"doc://org.cocoapods.Bricks/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVToastView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVToastView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVToastView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVToastView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVToastView\/title","value":"GVToastView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVToastView\/fragments","value":[{"kind":"identifier","text":"GVToastView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}