{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePicker"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/imagepicker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/imagepicker"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UINavigationControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/dismiss()","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/imagePickerControllerDidCancel(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/presentCamera(from:mediaTypes:onImageSelected:onVideoSelected:onCancel:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/presentPhotoLibrary(from:onImageSelected:onVideoSelected:onCancel:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/presentPhotoOnlyLibrary(from:onImageSelected:onCancel:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePicker"}],"title":"ImagePicker","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)ImagePicker","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"ImagePicker"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/presentCamera(from:mediaTypes:onImageSelected:onVideoSelected:onCancel:)":{"role":"symbol","title":"presentCamera(from:mediaTypes:onImageSelected:onVideoSelected:onCancel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"onImageSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"onVideoSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"onCancel"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/presentCamera(from:mediaTypes:onImageSelected:onVideoSelected:onCancel:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/imagepicker\/presentcamera(from:mediatypes:onimageselected:onvideoselected:oncancel:)"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/dismiss()":{"role":"symbol","title":"dismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/dismiss()","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/imagepicker\/dismiss()"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker":{"role":"symbol","title":"ImagePicker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePicker"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePicker"}],"url":"\/documentation\/bricks\/imagepicker"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/imagePickerControllerDidCancel(_:)":{"role":"symbol","title":"imagePickerControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/imagePickerControllerDidCancel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagePickerControllerDidCancel:"}],"url":"\/documentation\/bricks\/imagepicker\/imagepickercontrollerdidcancel(_:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/bricks\/imagepicker\/init"},"doc://org.cocoapods.Bricks/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)NSObject"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/presentPhotoLibrary(from:onImageSelected:onVideoSelected:onCancel:)":{"role":"symbol","title":"presentPhotoLibrary(from:onImageSelected:onVideoSelected:onCancel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentPhotoLibrary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onImageSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"onVideoSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"onCancel"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/presentPhotoLibrary(from:onImageSelected:onVideoSelected:onCancel:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/imagepicker\/presentphotolibrary(from:onimageselected:onvideoselected:oncancel:)"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIImagePickerControllerDelegate":{"type":"unresolvable","title":"UIImagePickerControllerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIImagePickerControllerDelegate"},"doc://org.cocoapods.Bricks/objc(pl)UINavigationControllerDelegate":{"type":"unresolvable","title":"UINavigationControllerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UINavigationControllerDelegate"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"role":"symbol","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"InfoKey","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/imagePickerController(_:didFinishPickingMediaWithInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"url":"\/documentation\/bricks\/imagepicker\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/ImagePicker/presentPhotoOnlyLibrary(from:onImageSelected:onCancel:)":{"role":"symbol","title":"presentPhotoOnlyLibrary(from:onImageSelected:onCancel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentPhotoOnlyLibrary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onImageSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"onCancel"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/presentPhotoOnlyLibrary(from:onImageSelected:onCancel:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/imagepicker\/presentphotoonlylibrary(from:onimageselected:oncancel:)"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ImagePicker"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ImagePicker"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImagePicker"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/imagePickerControllerDidCancel(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/ImagePicker\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UINavigationControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePicker"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1ImagePicker\/title","value":"ImagePicker"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1ImagePicker\/fragments","value":[{"kind":"identifier","text":"ImagePicker"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1ImagePicker~1imagePickerControllerDidCancel(_:)\/title","value":"imagePickerControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1ImagePicker~1imagePickerControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1ImagePicker~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title","value":"imagePickerController:didFinishPickingMediaWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1ImagePicker~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}