{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/keyboardtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/keyboardtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Different input type for OTP fields."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"title":"KeyboardType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Bricks@E@KeyboardType","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphaNumeric","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphabet","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/numeric"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/Equatable-Implementations","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/bricks\/keyboardtype\/rawrepresentable-implementations"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/bricks\/keyboardtype\/equatable-implementations"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/alphabet":{"role":"symbol","title":"KeyboardType.alphabet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphabet"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphabet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}],"url":"\/documentation\/bricks\/keyboardtype\/alphabet"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType":{"role":"symbol","title":"KeyboardType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"abstract":[{"type":"text","text":"Different input type for OTP fields."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardType"}],"url":"\/documentation\/bricks\/keyboardtype"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/alphaNumeric":{"role":"symbol","title":"KeyboardType.alphaNumeric","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphaNumeric"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphaNumeric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeAlphaNumeric"}],"url":"\/documentation\/bricks\/keyboardtype\/alphanumeric"},"doc://org.cocoapods.Bricks/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.Bricks\/SY"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/numeric":{"role":"symbol","title":"KeyboardType.numeric","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numeric"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/numeric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeNumeric"}],"url":"\/documentation\/bricks\/keyboardtype\/numeric"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/keyboardtype\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"KeyboardType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KeyboardType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"KeyboardType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphaNumeric","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/alphabet","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/numeric"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1alphabet\/title","value":"KeyboardTypeAlphabet"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1alphabet\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeAlphabet"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/title","value":"KeyboardType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/fragments","value":[{"kind":"identifier","text":"KeyboardType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1alphaNumeric\/title","value":"KeyboardTypeAlphaNumeric"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1alphaNumeric\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeAlphaNumeric"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1numeric\/title","value":"KeyboardTypeNumeric"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1numeric\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeNumeric"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}