{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/otpfieldviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/enteredOTP(otp:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/hasEnteredAllOTP(hasEnteredAll:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"title":"OTPFieldViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@Bricks@objc(pl)OTPFieldViewDelegate","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)":{"navigatorTitle":[{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"}],"role":"symbol","title":"shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otpTextFieldIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bricks\/otpfieldviewdelegate\/shouldbecomefirstresponderforotp(otptextfieldindex:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate/enteredOTP(otp:)":{"navigatorTitle":[{"kind":"identifier","text":"enteredOTPWithOtp:"}],"role":"symbol","title":"enteredOTP(otp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enteredOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"otp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/enteredOTP(otp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bricks\/otpfieldviewdelegate\/enteredotp(otp:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate/hasEnteredAllOTP(hasEnteredAll:)":{"navigatorTitle":[{"kind":"identifier","text":"hasEnteredAllOTPWithHasEnteredAll:"}],"role":"symbol","title":"hasEnteredAllOTP(hasEnteredAll:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasEnteredAllOTP"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hasEnteredAll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/hasEnteredAllOTP(hasEnteredAll:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bricks\/otpfieldviewdelegate\/hasenteredallotp(hasenteredall:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldViewDelegate":{"role":"symbol","title":"OTPFieldViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldViewDelegate"}],"url":"\/documentation\/bricks\/otpfieldviewdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"OTPFieldViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/enteredOTP(otp:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/hasEnteredAllOTP(hasEnteredAll:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldViewDelegate\/shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)\/title","value":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1shouldBecomeFirstResponderForOTP(otpTextFieldIndex:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldBecomeFirstResponderForOTPWithOtpTextFieldIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1enteredOTP(otp:)\/title","value":"enteredOTPWithOtp:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1enteredOTP(otp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enteredOTPWithOtp:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1hasEnteredAllOTP(hasEnteredAll:)\/title","value":"hasEnteredAllOTPWithHasEnteredAll:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate~1hasEnteredAllOTP(hasEnteredAll:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hasEnteredAllOTPWithHasEnteredAll:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/title","value":"OTPFieldViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldViewDelegate\/fragments","value":[{"kind":"identifier","text":"OTPFieldViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}