{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/displaytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/displaytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/circular","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/diamond","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/roundedCorner","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/square","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/underlinedBottom"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/Equatable-Implementations","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"title":"DisplayType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Bricks@E@DisplayType","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType":{"role":"symbol","title":"DisplayType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayType"}],"url":"\/documentation\/bricks\/displaytype"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/diamond":{"role":"symbol","title":"DisplayType.diamond","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diamond"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/diamond","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeDiamond"}],"url":"\/documentation\/bricks\/displaytype\/diamond"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/bricks\/displaytype\/rawrepresentable-implementations"},"doc://org.cocoapods.Bricks/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.Bricks\/SY"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/square":{"role":"symbol","title":"DisplayType.square","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"square"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/square","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeSquare"}],"url":"\/documentation\/bricks\/displaytype\/square"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/displaytype\/init(rawvalue:)"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/circular":{"role":"symbol","title":"DisplayType.circular","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"circular"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/circular","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeCircular"}],"url":"\/documentation\/bricks\/displaytype\/circular"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/underlinedBottom":{"role":"symbol","title":"DisplayType.underlinedBottom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlinedBottom"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/underlinedBottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeUnderlinedBottom"}],"url":"\/documentation\/bricks\/displaytype\/underlinedbottom"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/roundedCorner":{"role":"symbol","title":"DisplayType.roundedCorner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundedCorner"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/roundedCorner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}],"url":"\/documentation\/bricks\/displaytype\/roundedcorner"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/bricks\/displaytype\/equatable-implementations"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DisplayType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DisplayType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DisplayType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/circular","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/diamond","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/roundedCorner","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/square","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType\/underlinedBottom"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/title","value":"DisplayType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/fragments","value":[{"kind":"identifier","text":"DisplayType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1diamond\/title","value":"DisplayTypeDiamond"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1diamond\/fragments","value":[{"kind":"identifier","text":"DisplayTypeDiamond"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1square\/title","value":"DisplayTypeSquare"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1square\/fragments","value":[{"kind":"identifier","text":"DisplayTypeSquare"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1circular\/title","value":"DisplayTypeCircular"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1circular\/fragments","value":[{"kind":"identifier","text":"DisplayTypeCircular"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1underlinedBottom\/title","value":"DisplayTypeUnderlinedBottom"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1underlinedBottom\/fragments","value":[{"kind":"identifier","text":"DisplayTypeUnderlinedBottom"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1roundedCorner\/title","value":"DisplayTypeRoundedCorner"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType~1roundedCorner\/fragments","value":[{"kind":"identifier","text":"DisplayTypeRoundedCorner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}