{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIDocument"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSFilePresenter","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSProgressReporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/data"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/contents(forType:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/load(fromContents:ofType:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"title":"Document","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)Document","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"Document"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/objc(pl)NSProgressReporting":{"type":"unresolvable","title":"Foundation.ProgressReporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSProgressReporting"},"doc://org.cocoapods.Bricks/documentation/Bricks/Document":{"role":"symbol","title":"Document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Document"}],"url":"\/documentation\/bricks\/document"},"doc://org.cocoapods.Bricks/documentation/Bricks/Document/initWithFileURL:":{"role":"symbol","title":"initWithFileURL:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFileURL:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/initWithFileURL:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFileURL:"}],"url":"\/documentation\/bricks\/document\/initwithfileurl:"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/objc(cs)UIDocument":{"type":"unresolvable","title":"UIDocument","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UIDocument"},"doc://org.cocoapods.Bricks/documentation/Bricks/Document/contents(forType:)":{"role":"symbol","title":"contents(forType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"keyword","text":"Any"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/contents(forType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentsForType:error:"}],"url":"\/documentation\/bricks\/document\/contents(fortype:)"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/objc(pl)NSFilePresenter":{"type":"unresolvable","title":"Foundation.NSFilePresenter","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSFilePresenter"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks/Document/load(fromContents:ofType:)":{"role":"symbol","title":"load(fromContents:ofType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromContents"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ofType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/load(fromContents:ofType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadFromContents:ofType:error:"}],"url":"\/documentation\/bricks\/document\/load(fromcontents:oftype:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/Document/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/data","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/document\/data"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Document"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Document"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Document"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/contents(forType:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/initWithFileURL:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/Document\/load(fromContents:ofType:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIDocument"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIDocument","preciseIdentifier":"c:objc(cs)UIDocument"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document\/title","value":"Document"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document\/fragments","value":[{"kind":"identifier","text":"Document"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document~1contents(forType:)\/title","value":"contentsForType:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document~1contents(forType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contentsForType:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document~1load(fromContents:ofType:)\/title","value":"loadFromContents:ofType:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1Document~1load(fromContents:ofType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadFromContents:ofType:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}