{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVFieldView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvfieldview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvfieldview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextFieldDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/init(title:title2:placeholder:prefix:suffix:keyboardType:clearButtonMode:returnKeyType:titleFont:textFont:suffixSize:prefixSize:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/errorMessage","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/isEnabled","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onReturnPressed","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onTap","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/text","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textField"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/changeState(isEnabled:placeholderText:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onTextChanged(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/resignFirstResponder()","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textFieldShouldBeginEditing(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textFieldShouldReturn(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVFieldView"}],"title":"GVFieldView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVFieldView","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVFieldView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/text","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/text"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/onTap":{"role":"symbol","title":"onTap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTap"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onTap","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/ontap"},"doc://org.cocoapods.Bricks/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UITextFieldDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextFieldDelegate"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/onReturnPressed":{"role":"symbol","title":"onReturnPressed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReturnPressed"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onReturnPressed","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/onreturnpressed"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/onTextChanged(_:)":{"role":"symbol","title":"onTextChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/onTextChanged(_:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/ontextchanged(_:)"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/isEnabled","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/isenabled"},"doc://org.cocoapods.Bricks/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/changeState(isEnabled:placeholderText:)":{"role":"symbol","title":"changeState(isEnabled:placeholderText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/changeState(isEnabled:placeholderText:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/changestate(isenabled:placeholdertext:)"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.Bricks/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/errorMessage":{"role":"symbol","title":"errorMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/errorMessage","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/errormessage"},"doc://org.cocoapods.Bricks/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/init(title:title2:placeholder:prefix:suffix:keyboardType:clearButtonMode:returnKeyType:titleFont:textFont:suffixSize:prefixSize:)":{"role":"symbol","title":"init(title:title2:placeholder:prefix:suffix:keyboardType:clearButtonMode:returnKeyType:titleFont:textFont:suffixSize:prefixSize:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"suffix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"keyboardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardType","preciseIdentifier":"c:@E@UIKeyboardType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ViewMode","preciseIdentifier":"c:@E@UITextFieldViewMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnKeyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIReturnKeyType","preciseIdentifier":"c:@E@UIReturnKeyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"suffixSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prefixSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/init(title:title2:placeholder:prefix:suffix:keyboardType:clearButtonMode:returnKeyType:titleFont:textFont:suffixSize:prefixSize:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/init(title:title2:placeholder:prefix:suffix:keyboardtype:clearbuttonmode:returnkeytype:titlefont:textfont:suffixsize:prefixsize:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GVTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textField","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvfieldview\/textfield"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView":{"role":"symbol","title":"GVFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVFieldView"}],"url":"\/documentation\/bricks\/gvfieldview"},"doc://org.cocoapods.Bricks/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.Bricks/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UIView"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/textFieldShouldBeginEditing(_:)":{"role":"symbol","title":"textFieldShouldBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textFieldShouldBeginEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldBeginEditing:"}],"url":"\/documentation\/bricks\/gvfieldview\/textfieldshouldbeginediting(_:)"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/textFieldShouldReturn(_:)":{"role":"symbol","title":"textFieldShouldReturn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textFieldShouldReturn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}],"url":"\/documentation\/bricks\/gvfieldview\/textfieldshouldreturn(_:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVFieldView/resignFirstResponder()":{"role":"symbol","title":"resignFirstResponder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resignFirstResponder"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/resignFirstResponder()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resignFirstResponder"}],"url":"\/documentation\/bricks\/gvfieldview\/resignfirstresponder()"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVFieldView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVFieldView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVFieldView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/resignFirstResponder()","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textFieldShouldBeginEditing(_:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVFieldView\/textFieldShouldReturn(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextFieldDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVFieldView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView\/title","value":"GVFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView\/fragments","value":[{"kind":"identifier","text":"GVFieldView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView~1textFieldShouldBeginEditing(_:)\/title","value":"textFieldShouldBeginEditing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView~1textFieldShouldBeginEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldBeginEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView~1textFieldShouldReturn(_:)\/title","value":"textFieldShouldReturn:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView~1textFieldShouldReturn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldReturn:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView~1resignFirstResponder()\/title","value":"resignFirstResponder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVFieldView~1resignFirstResponder()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resignFirstResponder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}