{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvimage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIImage"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSItemProviderReading","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSItemProviderWriting","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSSecureCoding","doc:\/\/org.cocoapods.Bricks\/10Kingfisher19CacheCostCalculableP","doc:\/\/org.cocoapods.Bricks\/10Kingfisher0A10CompatibleP","doc:\/\/org.cocoapods.Bricks\/10Kingfisher11PlaceholderP","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIItemProviderPresentationSizeProviding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/getImage(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/ImageName"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVImage"}],"title":"GVImage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVImage","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVImage"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/10Kingfisher0A10CompatibleP":{"type":"unresolvable","title":"Kingfisher.KingfisherCompatible","identifier":"doc:\/\/org.cocoapods.Bricks\/10Kingfisher0A10CompatibleP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithCGImage:scale:orientation:":{"role":"symbol","title":"initWithCGImage:scale:orientation:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCGImage:scale:orientation:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCGImage:scale:orientation:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCGImage:scale:orientation:"}],"url":"\/documentation\/bricks\/gvimage\/initwithcgimage:scale:orientation:"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithCIImage:":{"role":"symbol","title":"initWithCIImage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCIImage:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCIImage:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCIImage:"}],"url":"\/documentation\/bricks\/gvimage\/initwithciimage:"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/bricks\/gvimage\/initwithcoder:"},"doc://org.cocoapods.Bricks/objc(cs)UIImage":{"type":"unresolvable","title":"UIImage","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UIImage"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSSecureCoding"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithContentsOfFile:":{"role":"symbol","title":"initWithContentsOfFile:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithContentsOfFile:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithContentsOfFile:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithContentsOfFile:"}],"url":"\/documentation\/bricks\/gvimage\/initwithcontentsoffile:"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/bricks\/gvimage\/init"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/objc(pl)NSItemProviderReading":{"type":"unresolvable","title":"Foundation.NSItemProviderReading","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSItemProviderReading"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIItemProviderPresentationSizeProviding":{"type":"unresolvable","title":"UIKit.UIItemProviderPresentationSizeProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIItemProviderPresentationSizeProviding"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/10Kingfisher19CacheCostCalculableP":{"type":"unresolvable","title":"Kingfisher.CacheCostCalculable","identifier":"doc:\/\/org.cocoapods.Bricks\/10Kingfisher19CacheCostCalculableP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithCGImage:":{"role":"symbol","title":"initWithCGImage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCGImage:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCGImage:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCGImage:"}],"url":"\/documentation\/bricks\/gvimage\/initwithcgimage:"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage":{"role":"symbol","title":"GVImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVImage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVImage"}],"url":"\/documentation\/bricks\/gvimage"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithData:":{"role":"symbol","title":"initWithData:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithData:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithData:"}],"url":"\/documentation\/bricks\/gvimage\/initwithdata:"},"doc://org.cocoapods.Bricks/10Kingfisher11PlaceholderP":{"type":"unresolvable","title":"Kingfisher.Placeholder","identifier":"doc:\/\/org.cocoapods.Bricks\/10Kingfisher11PlaceholderP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/getImage(_:)":{"role":"symbol","title":"getImage(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ImageName","preciseIdentifier":"s:6Bricks7GVImageC9ImageNameO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/getImage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvimage\/getimage(_:)"},"doc://org.cocoapods.Bricks/objc(pl)NSItemProviderWriting":{"type":"unresolvable","title":"Foundation.NSItemProviderWriting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSItemProviderWriting"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/ImageName":{"role":"symbol","title":"GVImage.ImageName","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageName"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/ImageName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageName"}],"url":"\/documentation\/bricks\/gvimage\/imagename"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithData:scale:":{"role":"symbol","title":"initWithData:scale:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:scale:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithData:scale:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:"}],"url":"\/documentation\/bricks\/gvimage\/initwithdata:scale:"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVImage/initWithCIImage:scale:orientation:":{"role":"symbol","title":"initWithCIImage:scale:orientation:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCIImage:scale:orientation:"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCIImage:scale:orientation:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCIImage:scale:orientation:"}],"url":"\/documentation\/bricks\/gvimage\/initwithciimage:scale:orientation:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVImage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVImage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/init","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCGImage:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCGImage:scale:orientation:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCIImage:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCIImage:scale:orientation:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithCoder:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithContentsOfFile:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithData:","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVImage\/initWithData:scale:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIImage"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVImage\/title","value":"GVImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVImage\/fragments","value":[{"kind":"identifier","text":"GVImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}