{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVLineButtonAbstract"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvlinebuttonabstract"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvlinebuttonabstract"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigLineButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigLineIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumLineButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumLineIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallLineButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallLineIconButton"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/10Kingfisher0A10CompatibleP","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract\/isEnabled"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract\/responseHandling()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVLineButtonAbstract"}],"title":"GVLineButtonAbstract","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVLineButtonAbstract","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVLineButtonAbstract"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBigLineIconButton":{"role":"symbol","title":"GVBigLineIconButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBigLineIconButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigLineIconButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBigLineIconButton"}],"url":"\/documentation\/bricks\/gvbiglineiconbutton"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMediumLineButton":{"role":"symbol","title":"GVMediumLineButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMediumLineButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumLineButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMediumLineButton"}],"url":"\/documentation\/bricks\/gvmediumlinebutton"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVBigLineButton":{"role":"symbol","title":"GVBigLineButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVBigLineButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigLineButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVBigLineButton"}],"url":"\/documentation\/bricks\/gvbiglinebutton"},"doc://org.cocoapods.Bricks/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVSmallLineButton":{"role":"symbol","title":"GVSmallLineButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVSmallLineButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallLineButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVSmallLineButton"}],"url":"\/documentation\/bricks\/gvsmalllinebutton"},"doc://org.cocoapods.Bricks/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVLineButtonAbstract/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract\/isEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/bricks\/gvlinebuttonabstract\/isenabled"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVRoundedButtonAbstract":{"role":"symbol","title":"GVRoundedButtonAbstract","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVRoundedButtonAbstract"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVRoundedButtonAbstract"}],"url":"\/documentation\/bricks\/gvroundedbuttonabstract"},"doc://org.cocoapods.Bricks/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContextMenuInteractionDelegate"},"doc://org.cocoapods.Bricks/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVLineButtonAbstract/responseHandling()":{"role":"symbol","title":"responseHandling()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseHandling"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract\/responseHandling()","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvlinebuttonabstract\/responsehandling()"},"doc://org.cocoapods.Bricks/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMediumLineIconButton":{"role":"symbol","title":"GVMediumLineIconButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMediumLineIconButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumLineIconButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMediumLineIconButton"}],"url":"\/documentation\/bricks\/gvmediumlineiconbutton"},"doc://org.cocoapods.Bricks/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Bricks/10Kingfisher0A10CompatibleP":{"type":"unresolvable","title":"Kingfisher.KingfisherCompatible","identifier":"doc:\/\/org.cocoapods.Bricks\/10Kingfisher0A10CompatibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVLineButtonAbstract":{"role":"symbol","title":"GVLineButtonAbstract","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVLineButtonAbstract"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVLineButtonAbstract"}],"url":"\/documentation\/bricks\/gvlinebuttonabstract"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVSmallLineIconButton":{"role":"symbol","title":"GVSmallLineIconButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVSmallLineIconButton"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallLineIconButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVSmallLineIconButton"}],"url":"\/documentation\/bricks\/gvsmalllineiconbutton"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVLineButtonAbstract"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVLineButtonAbstract"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVLineButtonAbstract"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVLineButtonAbstract\/isEnabled"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigLineButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVBigLineIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumLineButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMediumLineIconButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallLineButton","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVSmallLineIconButton"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVLineButtonAbstract"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVRoundedButtonAbstract","preciseIdentifier":"c:@M@Bricks@objc(cs)GVRoundedButtonAbstract","text":"GVRoundedButtonAbstract"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigLineIconButton\/title","value":"GVBigLineIconButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigLineIconButton\/fragments","value":[{"kind":"identifier","text":"GVBigLineIconButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumLineButton\/title","value":"GVMediumLineButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumLineButton\/fragments","value":[{"kind":"identifier","text":"GVMediumLineButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigLineButton\/title","value":"GVBigLineButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVBigLineButton\/fragments","value":[{"kind":"identifier","text":"GVBigLineButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallLineButton\/title","value":"GVSmallLineButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallLineButton\/fragments","value":[{"kind":"identifier","text":"GVSmallLineButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLineButtonAbstract~1isEnabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLineButtonAbstract~1isEnabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVRoundedButtonAbstract\/title","value":"GVRoundedButtonAbstract"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVRoundedButtonAbstract\/fragments","value":[{"kind":"identifier","text":"GVRoundedButtonAbstract"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumLineIconButton\/title","value":"GVMediumLineIconButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMediumLineIconButton\/fragments","value":[{"kind":"identifier","text":"GVMediumLineIconButton"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLineButtonAbstract\/title","value":"GVLineButtonAbstract"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVLineButtonAbstract\/fragments","value":[{"kind":"identifier","text":"GVLineButtonAbstract"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallLineIconButton\/title","value":"GVSmallLineIconButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVSmallLineIconButton\/fragments","value":[{"kind":"identifier","text":"GVSmallLineIconButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}