{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextField"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvtextfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvtextfield"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UITextField"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP","doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIKeyInput","doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDraggable","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDroppable","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextFieldDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInput","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInputTraits","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/init(maxCharacter:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/isError","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/padding"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/editingRect(forBounds:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/placeholderRect(forBounds:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/textRect(forBounds:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextField"}],"title":"GVTextField","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVTextField","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVTextField"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField/placeholderRect(forBounds:)":{"role":"symbol","title":"placeholderRect(forBounds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/placeholderRect(forBounds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholderRectForBounds:"}],"url":"\/documentation\/bricks\/gvtextfield\/placeholderrect(forbounds:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField":{"role":"symbol","title":"GVTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextField"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVTextField"}],"url":"\/documentation\/bricks\/gvtextfield"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearance"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField/editingRect(forBounds:)":{"role":"symbol","title":"editingRect(forBounds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editingRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/editingRect(forBounds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editingRectForBounds:"}],"url":"\/documentation\/bricks\/gvtextfield\/editingrect(forbounds:)"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField/isError":{"role":"symbol","title":"isError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/isError","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvtextfield\/iserror"},"doc://org.cocoapods.Bricks/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItem"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField/textRect(forBounds:)":{"role":"symbol","title":"textRect(forBounds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/textRect(forBounds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textRectForBounds:"}],"url":"\/documentation\/bricks\/gvtextfield\/textrect(forbounds:)"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UITextFieldDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextFieldDelegate"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField/init(maxCharacter:)":{"role":"symbol","title":"init(maxCharacter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxCharacter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/init(maxCharacter:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvtextfield\/init(maxcharacter:)"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.Bricks/objc(pl)UITextInput":{"type":"unresolvable","title":"UIKit.UITextInput","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInput"},"doc://org.cocoapods.Bricks/objc(pl)UITextPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UITextPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.Bricks/objc(pl)UIKeyInput":{"type":"unresolvable","title":"UIKit.UIKeyInput","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIKeyInput"},"doc://org.cocoapods.Bricks/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.Bricks/objc(cs)UITextField":{"type":"unresolvable","title":"UITextField","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UITextField"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.Bricks/7SnapKit25ConstraintRelatableTargetP":{"type":"unresolvable","title":"SnapKit.ConstraintRelatableTarget","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit25ConstraintRelatableTargetP"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/7SnapKit20LayoutConstraintItemP":{"type":"unresolvable","title":"SnapKit.LayoutConstraintItem","identifier":"doc:\/\/org.cocoapods.Bricks\/7SnapKit20LayoutConstraintItemP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContextMenuInteractionDelegate"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/objc(pl)UITextDraggable":{"type":"unresolvable","title":"UIKit.UITextDraggable","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDraggable"},"doc://org.cocoapods.Bricks/objc(pl)UITextInputTraits":{"type":"unresolvable","title":"UIKit.UITextInputTraits","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextInputTraits"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextField/padding":{"role":"symbol","title":"padding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/padding","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvtextfield\/padding"},"doc://org.cocoapods.Bricks/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/objc(pl)UITextDroppable":{"type":"unresolvable","title":"UIKit.UITextDroppable","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextDroppable"},"doc://org.cocoapods.Bricks/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.Bricks/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","title":"UIKit.UIContentSizeCategoryAdjusting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentSizeCategoryAdjusting"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVTextField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVTextField"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVTextField"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/editingRect(forBounds:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/placeholderRect(forBounds:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextField\/textRect(forBounds:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UITextField"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)UITextFieldDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField~1placeholderRect(forBounds:)\/title","value":"placeholderRectForBounds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField~1placeholderRect(forBounds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"placeholderRectForBounds:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField\/title","value":"GVTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField\/fragments","value":[{"kind":"identifier","text":"GVTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField~1editingRect(forBounds:)\/title","value":"editingRectForBounds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField~1editingRect(forBounds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editingRectForBounds:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField~1textRect(forBounds:)\/title","value":"textRectForBounds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextField~1textRect(forBounds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textRectForBounds:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}