{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVWebViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvwebviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvwebviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject","doc:\/\/org.cocoapods.Bricks\/s7CVarArgP","doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.Bricks\/SQ","doc:\/\/org.cocoapods.Bricks\/SH","doc:\/\/org.cocoapods.Bricks\/s8SendableP","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.Bricks\/objc(pl)WKNavigationDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)WKScriptMessageHandler"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/init(request:title:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/userContentController(_:didReceive:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVWebViewController"}],"title":"GVWebViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Bricks@objc(cs)GVWebViewController","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"GVWebViewController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks"]]},"references":{"doc://org.cocoapods.Bricks/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVWebViewController/init(request:title:)":{"role":"symbol","title":"init(request:title:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/init(request:title:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvwebviewcontroller\/init(request:title:)"},"doc://org.cocoapods.Bricks/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSExtensionRequestHandling"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVWebViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/bricks\/gvwebviewcontroller\/viewdidload()"},"doc://org.cocoapods.Bricks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.Bricks\/SQ"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVWebViewController/userContentController(_:didReceive:)":{"role":"symbol","title":"userContentController(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userContentController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKUserContentController","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/userContentController(_:didReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"url":"\/documentation\/bricks\/gvwebviewcontroller\/usercontentcontroller(_:didreceive:)"},"doc://org.cocoapods.Bricks/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIContentContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.Bricks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.Bricks\/s7CVarArgP"},"doc://org.cocoapods.Bricks/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.Bricks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSCoding"},"doc://org.cocoapods.Bricks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.Bricks\/SH"},"doc://org.cocoapods.Bricks/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(cs)UIViewController"},"doc://org.cocoapods.Bricks/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.Bricks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.Bricks\/s23CustomStringConvertibleP"},"doc://org.cocoapods.Bricks/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.Bricks/objc(pl)WKScriptMessageHandler":{"type":"unresolvable","title":"WKScriptMessageHandler","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)WKScriptMessageHandler"},"doc://org.cocoapods.Bricks/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.Bricks/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVWebViewController":{"role":"symbol","title":"GVWebViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVWebViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVWebViewController"}],"url":"\/documentation\/bricks\/gvwebviewcontroller"},"doc://org.cocoapods.Bricks/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.Bricks\/s8SendableP"},"doc://org.cocoapods.Bricks/objc(pl)WKNavigationDelegate":{"type":"unresolvable","title":"WKNavigationDelegate","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)WKNavigationDelegate"},"doc://org.cocoapods.Bricks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)NSObject"},"doc://org.cocoapods.Bricks/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.Bricks\/objc(pl)UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GVWebViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GVWebViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GVWebViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/userContentController(_:didReceive:)","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVWebViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.Bricks\/objc(pl)WKNavigationDelegate","doc:\/\/org.cocoapods.Bricks\/objc(pl)WKScriptMessageHandler"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVWebViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController~1userContentController(_:didReceive:)\/title","value":"userContentController:didReceiveScriptMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController~1userContentController(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController\/title","value":"GVWebViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVWebViewController\/fragments","value":[{"kind":"identifier","text":"GVWebViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}