{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvtextfieldbase\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvtextfieldbase\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextFieldBase\/intrinsicContentSize","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"intrinsicContentSize","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Bricks@objc(cs)GVTextFieldBase(py)intrinsicContentSize","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextFieldBase"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextFieldBase":{"role":"symbol","title":"GVTextFieldBase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVTextFieldBase"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextFieldBase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVTextFieldBase"}],"url":"\/documentation\/bricks\/gvtextfieldbase"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVTextFieldBase/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVTextFieldBase\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/bricks\/gvtextfieldbase\/intrinsiccontentsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextFieldBase\/title","value":"GVTextFieldBase"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextFieldBase\/fragments","value":[{"kind":"identifier","text":"GVTextFieldBase"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextFieldBase~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVTextFieldBase~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}