{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBInspectable"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvmultilinetextfield\/placeholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/gvmultilinetextfield\/placeholder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The string that is displayed when there is no other text in the text field."},{"type":"text","text":" "},{"type":"text","text":"This value is nil by default. The placeholder string is drawn using the color"},{"type":"text","text":" "},{"type":"text","text":"stored in "},{"type":"codeVoice","code":"self.placeholderColor"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"placeholder","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Bricks@objc(cs)GVMultilineTextField(py)placeholder","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField":{"role":"symbol","title":"GVMultilineTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"}],"abstract":[{"type":"text","text":"Text field with support for multiple lines."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMultilineTextField"}],"url":"\/documentation\/bricks\/gvmultilinetextfield"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField/placeholder":{"role":"symbol","title":"placeholder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The string that is displayed when there is no other text in the text field."},{"type":"text","text":" "},{"type":"text","text":"This value is nil by default. The placeholder string is drawn using the color"},{"type":"text","text":" "},{"type":"text","text":"stored in "},{"type":"codeVoice","code":"self.placeholderColor"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField\/placeholder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"url":"\/documentation\/bricks\/gvmultilinetextfield\/placeholder"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"placeholder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"placeholder"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"placeholder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/title","value":"GVMultilineTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/fragments","value":[{"kind":"identifier","text":"GVMultilineTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1placeholder\/title","value":"placeholder"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField~1placeholder\/fragments","value":[{"kind":"identifier","text":"placeholder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}