{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"closure"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVMultilineTextField","text":"GVMultilineTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/gvmultilineview\/ontextchanged(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineView\/onTextChanged(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"GVMultilineTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVMultilineTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"onTextChanged(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6Bricks15GVMultilineViewC13onTextChangedyyyAA0bE5FieldCcF","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineView":{"role":"symbol","title":"GVMultilineView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMultilineView"}],"url":"\/documentation\/bricks\/gvmultilineview"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineTextField":{"role":"symbol","title":"GVMultilineTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GVMultilineTextField"}],"abstract":[{"type":"text","text":"Text field with support for multiple lines."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GVMultilineTextField"}],"url":"\/documentation\/bricks\/gvmultilinetextfield"},"doc://org.cocoapods.Bricks/documentation/Bricks/GVMultilineView/onTextChanged(_:)":{"role":"symbol","title":"onTextChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTextChanged"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"GVMultilineTextField","preciseIdentifier":"c:@M@Bricks@objc(cs)GVMultilineTextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/GVMultilineView\/onTextChanged(_:)","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/gvmultilineview\/ontextchanged(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineView\/title","value":"GVMultilineView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineView\/fragments","value":[{"kind":"identifier","text":"GVMultilineView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/title","value":"GVMultilineTextField"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1GVMultilineTextField\/fragments","value":[{"kind":"identifier","text":"GVMultilineTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}