{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numeric"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/keyboardtype\/numeric"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/keyboardtype\/numeric"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/numeric","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numeric"}],"title":"KeyboardType.numeric","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Bricks@E@KeyboardType@KeyboardTypeNumeric","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeNumeric"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType/numeric":{"role":"symbol","title":"KeyboardType.numeric","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numeric"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType\/numeric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardTypeNumeric"}],"url":"\/documentation\/bricks\/keyboardtype\/numeric"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType":{"role":"symbol","title":"KeyboardType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"abstract":[{"type":"text","text":"Different input type for OTP fields."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardType"}],"url":"\/documentation\/bricks\/keyboardtype"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"KeyboardTypeNumeric"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeNumeric"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"KeyboardTypeNumeric"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1numeric\/title","value":"KeyboardTypeNumeric"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType~1numeric\/fragments","value":[{"kind":"identifier","text":"KeyboardTypeNumeric"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/title","value":"KeyboardType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/fragments","value":[{"kind":"identifier","text":"KeyboardType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}