{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldview\/awakefromnib()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bricks\/otpfieldview\/awakefromnib()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/awakeFromNib()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"title":"awakeFromNib()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Bricks@objc(cs)OTPFieldView(im)awakeFromNib","modules":[{"name":"Bricks"}],"navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/bricks\/otpfieldview\/awakefromnib()"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView":{"role":"symbol","title":"OTPFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldView"}],"url":"\/documentation\/bricks\/otpfieldview"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"awakeFromNib"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/title","value":"OTPFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/fragments","value":[{"kind":"identifier","text":"OTPFieldView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}