{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType","preciseIdentifier":"c:@M@Bricks@E@DisplayType","text":"DisplayType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldview\/displaytype"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/displayType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Different display type for text fields."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayType","preciseIdentifier":"c:@M@Bricks@E@DisplayType"}],"title":"displayType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Bricks12OTPFieldViewC11displayTypeAA07DisplayE0Ovp","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView/displayType":{"role":"symbol","title":"displayType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DisplayType","preciseIdentifier":"c:@M@Bricks@E@DisplayType"}],"abstract":[{"type":"text","text":"Different display type for text fields."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/displayType","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/otpfieldview\/displaytype"},"doc://org.cocoapods.Bricks/documentation/Bricks/DisplayType":{"role":"symbol","title":"DisplayType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/DisplayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DisplayType"}],"url":"\/documentation\/bricks\/displaytype"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView":{"role":"symbol","title":"OTPFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldView"}],"url":"\/documentation\/bricks\/otpfieldview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/title","value":"DisplayType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1DisplayType\/fragments","value":[{"kind":"identifier","text":"DisplayType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/title","value":"OTPFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/fragments","value":[{"kind":"identifier","text":"OTPFieldView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}