{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"otpInputType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType","preciseIdentifier":"c:@M@Bricks@E@KeyboardType","text":"KeyboardType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bricks\/otpfieldview\/otpinputtype"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/otpInputType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"otpInputType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardType","preciseIdentifier":"c:@M@Bricks@E@KeyboardType"}],"title":"otpInputType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Bricks12OTPFieldViewC12otpInputTypeAA08KeyboardF0Ovp","modules":[{"name":"Bricks"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView"]]},"references":{"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView":{"role":"symbol","title":"OTPFieldView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTPFieldView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OTPFieldView"}],"url":"\/documentation\/bricks\/otpfieldview"},"doc://org.cocoapods.Bricks/documentation/Bricks":{"role":"collection","title":"Bricks","abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks","kind":"symbol","type":"topic","url":"\/documentation\/bricks"},"doc://org.cocoapods.Bricks/documentation/Bricks/KeyboardType":{"role":"symbol","title":"KeyboardType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardType"}],"abstract":[{"type":"text","text":"Different input type for OTP fields."}],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/KeyboardType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeyboardType"}],"url":"\/documentation\/bricks\/keyboardtype"},"doc://org.cocoapods.Bricks/documentation/Bricks/OTPFieldView/otpInputType":{"role":"symbol","title":"otpInputType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"otpInputType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"KeyboardType","preciseIdentifier":"c:@M@Bricks@E@KeyboardType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.Bricks\/documentation\/Bricks\/OTPFieldView\/otpInputType","kind":"symbol","type":"topic","url":"\/documentation\/bricks\/otpfieldview\/otpinputtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/title","value":"OTPFieldView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1OTPFieldView\/fragments","value":[{"kind":"identifier","text":"OTPFieldView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/title","value":"KeyboardType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.Bricks~1documentation~1Bricks~1KeyboardType\/fragments","value":[{"kind":"identifier","text":"KeyboardType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}